In [66]:
#import packages
import pandas as pd
import numpy as np

In [67]:
df1 = pd.read_csv('Fake.csv')
df2 = pd.read_csv('True.csv')

### EDA

In [68]:
df1.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [69]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23481 entries, 0 to 23480
Data columns (total 4 columns):
title      23481 non-null object
text       23481 non-null object
subject    23481 non-null object
date       23481 non-null object
dtypes: object(4)
memory usage: 733.9+ KB

In [70]:
df2.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [71]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21417 entries, 0 to 21416
Data columns (total 4 columns):
title      21417 non-null object
text       21417 non-null object
subject    21417 non-null object
date       21417 non-null object
dtypes: object(4)
memory usage: 669.4+ KB

Assign target y

In [72]:
df1['target'] = [1 for i in range(len(df1))]

In [73]:
df2['target'] = [0 for i in range(len(df2))]

In [74]:
# Merge 2 dataframes

df = pd.concat([df1, df2], ignore_index=True)

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44898 entries, 0 to 44897
Data columns (total 5 columns):
title      44898 non-null object
text       44898 non-null object
subject    44898 non-null object
date       44898 non-null object
target     44898 non-null int64
dtypes: int64(1), object(4)
memory usage: 1.7+ MB

In [76]:
df.tail()

,title,text,subject,date,target
44893,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",0
44894,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",0
44895,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",0
44896,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",0
44897,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",0

In [77]:
# clean data

import re
import nltk

def basic_clean(text):
    wnl = nltk.stem.WordNetLemmatizer()
    stopwords = nltk.corpus.stopwords.words('english')
    words = nltk.tokenize.word_tokenize(text)
    words = [w.lower() for w in words]
    temp = [word for word in words if re.search('^[a-z]+$', word)]
    temp2 = [wnl.lemmatize(word) for word in temp if word not in stopwords]
    return " ".join(temp2)

In [78]:
df['text_aft'] = df['text'].map(basic_clean)

In [79]:
df['title_aft'] = df['title'].map(basic_clean)

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44898 entries, 0 to 44897
Data columns (total 7 columns):
title        44898 non-null object
text         44898 non-null object
subject      44898 non-null object
date         44898 non-null object
target       44898 non-null int64
text_aft     44898 non-null object
title_aft    44898 non-null object
dtypes: int64(1), object(6)
memory usage: 2.4+ MB

In [81]:
df.tail()

,title,text,subject,date,target,text_aft,title_aft
44893,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",0,brussels reuters nato ally tuesday welcomed pr...,committed nato back new approach afghanistan
44894,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",0,london reuters lexisnexis provider legal regul...,lexisnexis withdrew two product chinese market
44895,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",0,minsk reuters shadow disused factory minsk str...,minsk cultural hub becomes authority
44896,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",0,moscow reuters vatican secretary state cardina...,vatican upbeat possibility pope francis visiti...
44897,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",0,jakarta reuters indonesia buy sukhoi fighter j...,indonesia buy billion worth russian jet

In [98]:
# replace empty cell with NaN value
df = df.replace(r'^\s*$', np.NaN, regex=True)

In [99]:
# check rows with null values
df[df.isnull().any(axis=1)]

,title_aft,text_aft,subject,date,target
10923,take poll think president trump pick replace j...,NaN,politics,"May 10, 2017",1
11041,joe scarborough berates mika brzezinski cheap ...,NaN,politics,"Apr 26, 2017",1
11190,watch tucker carlson scorch sanctuary city may...,NaN,politics,"Apr 6, 2017",1
11225,mayor sanctuary city trump trying make u fugit...,NaN,politics,"Apr 2, 2017",1
11236,shocker public school turn computer lab studen...,NaN,politics,"Apr 1, 2017",1
11241,boom sean spicer trump sold hotel russia hilla...,NaN,politics,"Mar 31, 2017",1
11247,michael flynn lawyer release statement scorchi...,NaN,politics,"Mar 30, 2017",1
11249,rob schneider nail russia conspiracy theorist ...,NaN,politics,"Mar 30, 2017",1
11267,trey gowdy spying american president trump video,NaN,politics,"Mar 28, 2017",1
11268,sean spicer call race baiting journalist stop ...,NaN,politics,"Mar 28, 2017",1
11283,boom trey gowdy shoot outrage intel chair brie...,NaN,politics,"Mar 27, 2017",1
11284,unreal cbs ted koppel tell sean hannity bad am...,NaN,politics,"Mar 27, 2017",1
11285,senior cia intel wiretapping trump transition ...,NaN,politics,"Mar 27, 2017",1
11289,horrible end game bernie sander call socialize...,NaN,politics,"Mar 26, 2017",1
11290,reince priebus interview speaker ryan blame he...,NaN,politics,"Mar 26, 2017",1
11292,fake news alert former gov maryland call boyco...,NaN,politics,"Mar 26, 2017",1
11295,judge hit street ask whose fault healthcare bi...,NaN,politics,"Mar 25, 2017",1
11296,judge jeanine fire paul ryan need step house s...,NaN,politics,"Mar 25, 2017",1
11301,lawyer illegal alien rapist hysteria rape old ...,NaN,politics,"Mar 25, 2017",1
11303,newt gingrich one trump lot personnel change t...,NaN,politics,"Mar 25, 2017",1
11304,outrageous nancy pelosi claim obamacare honor ...,NaN,politics,"Mar 25, 2017",1
11305,intel whistleblower trump likely spied easy am...,NaN,politics,"Mar 25, 2017",1
11309,watch full response trump obamacare vote obama...,NaN,politics,"Mar 24, 2017",1
11314,nancy pelosi try lead democrat chant fail video,NaN,politics,"Mar 24, 2017",1
11317,house intel chair obama administration spying ...,NaN,politics,"Mar 23, 2017",1
11319,fake cnn msnbc caught claiming live aired time...,NaN,politics,"Mar 23, 2017",1
11322,sean spicer hit lame cnn let actually look cnn...,NaN,politics,"Mar 23, 2017",1
11330,brilliant tucker carlson ayaan hirsi ali discu...,NaN,politics,"Mar 22, 2017",1
11334,nancy pelosi asked leader dems guess soros video,NaN,politics,"Mar 22, 2017",1
11335,angel mom son killed illegals weigh rockville ...,NaN,politics,"Mar 22, 2017",1
...,...,...,...,...,...
19844,flashback bill clinton sexual relation woman v...,NaN,left-news,"Oct 8, 2016",1
19845,flashback president colorful two play game video,NaN,left-news,"Oct 8, 2016",1
19846,hillary clinton rape enabler kind monster video,NaN,left-news,"Oct 8, 2016",1
19863,funny msnbc anchor asks millennial woman feel ...,NaN,left-news,"Oct 5, 2016",1
19867,unreal obama blame syrian civil war climate we...,NaN,left-news,"Oct 5, 2016",1
19895,thinking disheveled obama yell air force one b...,NaN,left-news,"Oct 1, 2016",1
19899,muslim woman busted buying soda food stamp sto...,NaN,left-news,"Sep 29, 2016",1
19935,video destroy black life matter everywhere,NaN,left-news,"Sep 22, 2016",1
19973,one creepy tweet hillary parent saying hand kid,NaN,left-news,"Sep 15, 2016",1
20029,cnn panel roar laughter tim kaine lame defense...,NaN,left-news,"Sep 4, 2016",1
20394,classic college snowflake demolished great and...,NaN,left-news,"Jun 20, 2016",1
20715,feel bern paycheck look like bernie president,NaN,left-news,"Apr 19, 2016",1
21237,mark steyn hammer democrat climate change scam...,NaN,left-news,"Dec 10, 2015",1
21584,duke hazard video eerily predicts must watch,NaN,left-news,"Jul 8, 2015",1
21714,must watch comedy room full dems asked name on...,NaN,left-news,"May 20, 2015",1
21715,store owner bash liberal obamaites shuts door ...,NaN,left-news,"May 20, 2015",1
21751,wacko liberal pundit good news isi attack smal...,NaN,left-news,"May 11, 2015",1
21775,megyn kelly set confused liberal straight free...,NaN,left-news,"May 6, 2015",1
21780,outrageous video obama keep stirring flame div...,NaN,left-news,"May 5, 2015",1
21785,black republican brilliant neurosurgeon announ...,NaN,left-news,"May 5, 2015",1
21786,video baltimore mayor reopens looted mall tell...,NaN,left-news,"May 4, 2015",1
21787,video pam geller hammer cnn host christian bur...,NaN,left-news,"May 4, 2015",1
21813,video mom year mom catch rioting beat live tv,NaN,left-news,"Apr 27, 2015",1
21815,video rioter take selfies torched police car,NaN,left-news,"Apr 27, 2015",1
21816,baltimore burn maryland governor brings nation...,NaN,left-news,"Apr 27, 2015",1
21826,full video blockbuster investigation clinton cash,NaN,left-news,"Apr 25, 2015",1
21827,video hillary clinton religious belief must ch...,NaN,left-news,"Apr 25, 2015",1
21857,video ice protecting obama release name crimin...,NaN,left-news,"Apr 14, 2015",1
21873,video hysterical snl take hillary announcement...,NaN,left-news,"Apr 12, 2015",1
32451,graphic supreme court roundup,NaN,politicsNews,"June 16, 2016",0

In [ ]:
# drop original data columns to reduce volume to store
df = df.drop(['text', 'title'], axis=1)

In [94]:
df = df[['title_aft', 'text_aft','subject', 'date', 'target']]

In [95]:
df.head()

,title_aft,text_aft,subject,date,target
0,donald trump sends embarrassing new year eve m...,donald trump wish american happy new year leav...,News,"December 31, 2017",1
1,drunk bragging trump staffer started russian c...,house intelligence committee chairman devin nu...,News,"December 31, 2017",1
2,sheriff david clarke becomes internet joke thr...,friday revealed former milwaukee sheriff david...,News,"December 30, 2017",1
3,trump obsessed even obama name coded website i...,christmas day donald trump announced would bac...,News,"December 29, 2017",1
4,pope francis called donald trump christmas speech,pope francis used annual christmas day message...,News,"December 25, 2017",1

In [101]:
df = df.dropna()

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 44266 entries, 0 to 44897
Data columns (total 5 columns):
title_aft    44266 non-null object
text_aft     44266 non-null object
subject      44266 non-null object
date         44266 non-null object
target       44266 non-null int64
dtypes: int64(1), object(4)
memory usage: 2.0+ MB

In [103]:
#convert to csv file
df.to_csv('news_processed.csv', index=False)